name: 'rumlisp_dart'
description: 'Dart implementation of rumlisp language.'
version: 1.0.0
homepage: https://github.com/RuMaxwell/rumlisp_dart
author: RuMaxwell <935906960@qq.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  path: ^1.4.1
  args: ^1.5.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
